# Generated by Django 4.0.5 on 2022-10-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "command",
                    models.CharField(
                        choices=[("ON", "On"), ("OFF", "Off"), ("TOG", "Tog")],
                        default="TOG",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_on", models.BooleanField()),
            ],
        ),
    ]
