# Generated by Django 4.0.5 on 2022-10-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heating_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledevent",
            name="command",
            field=models.CharField(
                choices=[("ON", "On"), ("OFF", "Off"), ("TOG", "Toggle")],
                default="TOG",
                max_length=6,
            ),
        ),
    ]
