# Generated by Django 4.0.5 on 2022-10-27 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heating_control', '0002_alter_scheduledevent_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
