# Generated by Django 4.0.5 on 2022-11-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating_control', '0003_alter_scheduledevent_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='repeat',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('None', 'None')], default='None', max_length=6),
        ),
    ]
