# Generated by Django 4.0.5 on 2022-12-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating_control', '0004_scheduledevent_deleted_scheduledevent_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
