# Generated by Django 4.0.5 on 2022-12-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating_control', '0005_aggusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggusage',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
