# Generated by Django 4.0.5 on 2022-07-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartswitch',
            options={'ordering': ['name']},
        ),
    ]
