# Generated by Django 4.0.5 on 2022-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_switch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockswitch",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
